### ISSUE TITLE
Centos

### ISSUE THREAD

**Issue by jamimes** [Neilpang/le#1]
[root@s2 le]# le issue   /data/wwwroot/xxxxx.com    xxxxx.com    www.xxxxx.com
Use default length 2048
Generating RSA private key, 2048 bit long modulus
................................................................................................................................+++
.........................................................................................+++
e is 65537 (0x10001)
Use default length 2048
Generating RSA private key, 2048 bit long modulus
.........................+++
......................................+++
e is 65537 (0x10001)
multi domain DNS:www.xxxxx.com
cat: /etc/ssl/openssl.cnf: No such file or directory
unable to find 'distinguished_name' in config
problems making Certificate Request
140032319231816:error:0E06D06C:configuration file routines:NCONF_get_string:no value:conf_lib.c:335:group=req name=distinguished_name
Registering account
Registered
verify each domain
Verifing domain xxxxx.com
verify error:xxxxx.com

----------------------------------------------------------------------
[root@s2 le]# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6
Codename:	Final

**Comment by chemzqm** [comment]
跟我碰到情况一样，应该是 404 了，你要确保它生成 .well-known 目录是可以用 http 访问的，
在 nginx 可以这么加：

root /var/www/html;
  location /.well-known {
    try_files $uri $uri/ =404;
  }

这一条 location 放到其它的上面

**Comment by jamimes** [comment]
应该不是你说的这个原因吧？

**Comment by Neilpang** [comment]
不是的,  这个issue 是因为 centos上的 openssl的 conf 文件找不到.  我明天开个 centos 虚机,然后修复.

**Comment by wangqiliang** [comment]
我也遇到同样的问题，openssl.cnf找不到，生成的证书长度很诡异，cat了一下，begin ssl certificate下面，第一个字符是E【按理来说应该是M。

**Comment by Neilpang** [comment]
openssl.cnf 已经修复.

**Comment by wangqiliang** [comment]
我在/etc/pki/ssl找到了openssl.cnf，复制一份即可。

**Comment by Neilpang** [comment]
不需要了,  已经移除了对 opensslssl.cnf   的依赖

**Comment by jamimes** [comment]
刚刚测试过了。成功生成证书了

**Comment by Neilpang** [comment]
多谢.
