### ISSUE TITLE
Reuse existing key

### ISSUE THREAD

**Issue by AnLAdmin** [Neilpang/le#103]
Hi

Is it possible to use an existing domain key (e.g. preliminarily self signed)? If not, it would be nice if one can only create a CSR for an existing key.

Regards
Frank

**Comment by Neilpang** [comment]
you can copy the key to `~/.le/domain.com/domain.com.key`

Then `le` will use this key.

**Comment by AnLAdmin** [comment]
Ah, well, it didn't work.
This is the print out (le dns host.mydomain.com no no), first run:
Creating account key
Use default length 2048
Creating domain key
Use length 2048
Domain key exists, do you want to overwrite the key?
Set FORCE=1, and try again.
Create domain key error.
