### ISSUE TITLE
通过浏览器访问OK, 但是在微信里打开时，nginx 日志显示 400

### ISSUE THREAD

**Issue by zhoumengkang** [Neilpang/le#106]
```nginx
		listen       80;
		listen	     443 ssl;
			
		ssl on;
		ssl_certificate      /root/.le/xxx.com/xxx.com.cer;
        	ssl_certificate_key  /root/.le/xxx.com/xxx.com.key;
```
1. 在PC上通过浏览器访问都OK，但是在微信里去打不开，在QQ里也同样。是我的配置写得不完整么？nginx 日志有访问请求，错误日志无报错，请求日志为 400

2. 还有一个问题，在PC的safari里打开OK，但是在手机里用safari打开无法加载子域名的资源（子域名一起生成的证书）。

**Comment by Neilpang** [comment]
1.  建议不要直接使用  .le  里面的文件.  `/root/.le/xxx.com/xxx.com.cer`
你应该把里面的证书拷贝到 nginx 的专门的放证书的文件夹.

2. 请使用 `/root/.le/xxx.com/fullchain.cer`,  而不是 `/root/.le/xxx.com/xxx.com.cer`.   因为 fullchain.cer 里面包含证书链.

当然你也可以手动合并 `/root/.le/xxx.com/xxx.com.cer`  和 `/root/.le/xxx.com/ca.cer` 来构成 fullchain.cer

3. 请将生成的证书拷贝到 这里:  `https://www.trustasia.com/tools/cert-decoder.htm`
自己验证一下里面的 主题 以及 `sans` 字段, 是否包含了你的主域名和所有的子域名.

**Comment by zhoumengkang** [comment]
难道那个脚本有bug，我用的 https://github.com/Neilpang/le/tree/master/dnsapi#use-dnspodcn-domain-api-to-automatically-issue-cert 这种方式生成的，好想没有你说的那个脚本。我先手动合并下。

**Comment by Neilpang** [comment]
你的版本太久了吧.
uninstall
然后重新install

你的数据都会保留,不会丢失.

**Comment by zhoumengkang** [comment]
哦，好，我重新试试看。

**Comment by zhoumengkang** [comment]
@Neilpang 你的意思是我重新更下最新的脚本，然后重新执行一次
```sh
le.sh   issue   dns-dp   aa.com  www.aa.com
```
数据不会丢失，是吧？

**Comment by zhoumengkang** [comment]
@Neilpang 手动合并之后，好了！在说明文档中没有看到自动更新的说明，我在crontab里只看到了一句
```sh
0 0 * * * LE_WORKING_DIR="/root/.le" "/root/.le"/le.sh cron > /dev/null
```
这个就是那个自动更新么？我可以不用管更新了，是吧？

**Comment by Neilpang** [comment]
是的，  默认每 80天会自动 renew 证书。
但是， 每次renew 证书之后， 可能需要 执行 `service  nginx reload` 来让nginx 重新加载证书。

请在 `/root/.le/xxx.com/xxx.com.conf`  文件中找到  `Le_ReloadCmd` 改为：
```
Le_ReloadCmd="/usr/sbin/service   nginx   reload "
```

这样就可以每次自动加载了。

这些步骤本来都是可以自动化的。

请参见： `le   installcert  ..........  `  这个命令。

**Comment by zhoumengkang** [comment]
```sh
Le_Keylength=
Le_RealCertPath=""
Le_RealCACertPath=""
Le_RealKeyPath=""
Le_ReloadCmd=""
Le_Vlist=""
```
我改成
```sh
Le_Keylength=
Le_RealCertPath="/root/.le/xxx.com/fullchain.cer"
Le_RealCACertPath="/root/.le/xxx.com/xxx.com.csr"
Le_RealKeyPath="/root/.le/xxx.com/xxx.com.key"
Le_ReloadCmd="/usr/sbin/service nginx restart"
Le_Vlist=""
```
对么，其中，长度填多少，下面那个Vlist 填什么呢，谢啦。
是因为是比较老的脚本生成的，所以没有么？

**Comment by Neilpang** [comment]
No

千万不要改其他的几个，  只改  `Le_ReloadCmd`

**Comment by Neilpang** [comment]
如果你不是明确的知道它们的意义，  请不要任意修改。

**Comment by zhoumengkang** [comment]
哦，好的，只配置了`Le_ReloadCmd `，没有看到文档中有关这个的说明呢，谢谢解答。希望到时候能更新成功。
