### ISSUE TITLE
is possible to use a custom port in standalone mode?

### ISSUE THREAD

**Issue by pescobar** [Neilpang/le#107]
I need to issue/renew a certificate for three different subdomains and each of the web applications run in different docker container. I have another container running haproxy listening in port 80 and 443 which forwards the traffic to the right container based on the subdomain in the url. 

I think the easiest approach to be able to renew the certificate would be to run the client in standalone mode using a custom port (not 80 or 443). Is this possible or should I look for a different solution?

**Comment by cleverfox** [comment]
It is useless, because Let’s Encrypt supports verification only on ports 80 and 443

**Comment by pescobar** [comment]
thanks for the clarification @cleverfox. I was not aware of this. do you know why letencrypt doesn't support custom ports? I think it would be useful for use cases like mine.

I think I will configure haproxy to capture url `.well-known` so it forwards any request containing this url to a custom docker container where I will do the certificate renewal

**Comment by cleverfox** [comment]
@pescobar yes, this solution works good. I doing same way, but with nginx.
