### ISSUE TITLE
cloudflare dns mode

### ISSUE THREAD

**Issue by qiaoyan** [Neilpang/le#108]
Hi, may be a silly question. after enable cloudflare dns mode, how the cloudflare server talk to my host server? throught http or https or something else?  my host server nginx need .crt and .key file to enable ssl but I can't find the crt file. Thanks.

**Comment by qiaoyan** [comment]
below link describe how to convert .cer file to .crt, but let's encrypt do renew every 3 months so might need add .crt file to auto renew script? thanks.
------
http://stackoverflow.com/questions/642284/apache-with-ssl-how-to-convert-cer-to-crt-certificates

**Comment by heldchen** [comment]
nginx and apache can read the .cer file just fine.

**Comment by Neilpang** [comment]
cer == crt

They are all  pem formated:   base64 encoded der data,  or  base64 encoded asn.1 encoded x509 data.

**Comment by qiaoyan** [comment]
Thanks. I use nginx docker image instead of build myself. the following docker image only process with .crt file, any suggestion to automatically copy .cer to .crt in renew script? 

https://hub.docker.com/r/jwilder/nginx-proxy/

**Comment by qiaoyan** [comment]
Hi, my current solution with nginx docker reverse proxy capability is here:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
