### ISSUE TITLE
can't retry

### ISSUE THREAD

**Issue by MarcusWolschon** [Neilpang/le#112]
./le.sh issue mydomain.info www.mydomain.info /home/domains/mydomain.info/htdocs/ ec-384
Creating account key
Registering account
Registered
Creating domain key
Use length 384
Using ec name: secp384r1
Creating csr
Multi domain=DNS:/home/domains/mydomain.info/htdocs/
Verify each domain
Getting token for domain=www.mydomain.info
Getting token for domain=/home/domains/mydomain.info/htdocs/
new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Invalid character in DNS name","status":400}

If this is about the "/" in the path, it's highly misleading since that slash is no part of any domain name.

./le.sh issue mydomain.info www.mydomain.info /home/domains/mydomain.info/htdocs ec-384
Creating account key
Account key exists, skip
Skip register account key
Creating domain key
Use length 384
Using ec name: secp384r1
Domain key exists, do you want to overwrite the key?
Set FORCE=1, and try again.
Create domain key error.

Aparently the script is not cleaning up after itself, if it fails.

./le.sh issue mydomain.info www.mydomain.info /home/domains/mydomain.info/htdocs ec-384 FORCE=1
Creating account key
Account key exists, skip
Skip register account key
Creating domain key
Use length 384
Using ec name: secp384r1
Domain key exists, do you want to overwrite the key?
Set FORCE=1, and try again.
Create domain key error.

There is no obvious way to "set FORCE=1" and no message that I should remove any specific (key-) file.

**Comment by heldchen** [comment]
your parameters are in the wrong order. use ` le issue  /home/domains/mydomain.info/htdocs mydomain.info www.mydomain.info`

**Comment by MarcusWolschon** [comment]
It still doesn't clean up after itself after a failure and still asks me to specify a FORCE="1" parameter with no information where to set it.

**Comment by heldchen** [comment]
it's an environment variable, so... `FORCE=1 le issue /home/domains/mydomain.info/htdocs mydomain.info www.mydomain.info`

**Comment by MarcusWolschon** [comment]
So let's fix the cleaning-up part (evaluate return codes) and change or anotate that error-message to say exactly that. (or add it to the help-page)

**Comment by heldchen** [comment]
you are welcome...

the non-cleanup is intentional, as there can be temporary errors and in these cases, a `renew` can be used to retry.

feel free to submit pull requests for docs, I guess the maintainer of this script will happily merge any useful change.

**Comment by MarcusWolschon** [comment]
Maybe I will.
For now, it just needs to stay documented here as a known issue that someone can work on.

**Comment by Neilpang** [comment]
Please read the doc for the usage:

https://github.com/Neilpang/le#just-issue-a-cert

**Comment by MarcusWolschon** [comment]
What does the documentation have to do with some missing details in an error message?

**Comment by Neilpang** [comment]
So, what do you expect the readme to be like?   Just send a pullrequest.
Thanks.

**Comment by tallship** [comment]
@MarcusWolschon 

./le.sh issue mydomain.info www.mydomain.info /home/domains/mydomain.info/htdocs ec-384

I don't think you need the www hostname - when just creating a cert for a cannonical domain name they usually include that (mydomain.info) as well as the www hostname (www.mydomain.info).

Contrariwise, when you create a cert for a www hostname (www.mydomain.info) it only creates a cert for that particular hostname and NOT the canonical domain (mydomain.info).

And the format, as pointed out before, for the webroot methhod is:

le issue /home/domains/mydomain.info/htdocs domain.info

That would create a cert good for mydomain.info AND www.mydomain.info, if I'm not mistaken.

so it would be correct to say:

le issue /home/domains/mydomain.info/htdocs domain.info www.domain.info

As far as the error where you need to pass the environment variable, you could just wipe the directory for your domain.info domain under ~/.le/ and run the command again.

YMMV, so let us know how this works for you Marcus :)

I'm working on a new readme file with more complete instructions as well as preparing man pages for Neil, as a thank you for all of his hard work and effort in developing this free software for you - I'll try to address your concerns in that pull request.
