### ISSUE TITLE
DNS label to short

### ISSUE THREAD

**Issue by Richard87** [Neilpang/le#113]
I have a problem with le.sh, not sure how to fix it:
(current directory is webroot of domain)

	[root@legetimen]# FORCE=1 le issue webroot . www.legetimen.no,legetimen.no
	Creating account key
	Use default length 2048
	Account key exists, skip
	Skip register account key
	Creating domain key
	Use length 2048
	Creating csr
	Multi domain=DNS:www.legetimen.no,DNS:legetimen.no
	Verify each domain
	Getting token for domain=.
	new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: DNS label is too short","status":400}

Please help :)

**Comment by heldchen** [comment]
you want `FORCE=1 le issue . legetimen.no www.legetimen.no`

**Comment by Richard87** [comment]
It fails with this error:

	[root@legetimen ]# FORCE=1 le issue webroot . legetimen.no www.legetimen.no
	Creating account key
	Account key exists, skip
	Skip register account key
	Creating domain key
	Use length www.legetimen.no
	Create domain key error.

I do get key and csr in `/root/.le/www.legetimen.no`
Also the configuration is as follows:

	Le_Domain=www.legetimen.no
	Le_Alt=
	Le_Webroot=legetimen.no
	Le_Keylength=
	Le_RealCertPath=""
	Le_RealCACertPath=""
	Le_RealKeyPath=""
	Le_ReloadCmd=""
		
And the webroot should be in `/var/www/www.legetimen.no/www`, so I'm pretty sure that's wrong to...

**Comment by heldchen** [comment]
again, remove the "webroot" part from your command: 
`[root@legetimen ]# FORCE=1 le issue . legetimen.no www.legetimen.no``

**Comment by Richard87** [comment]
Also tried to specify webroot, but this failed misreably:

	[root@legetimen www.legetimen.no]# FORCE=1 le issue webroot
	Usage: le  issue  webroot|no|apache|dns   a.com  [www.a.com,b.com,c.com]|no   [key-length]|no
	[root@legetimen www.legetimen.no]# FORCE=1 le issue webroot  /var/www/www.legetimen.no/www/ legetimen.no www.legetimen.no
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	touch: cannot touch `/root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf': No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	/root/.le/le.sh: line 566: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	grep: /root/.le//var/www/www.legetimen.no/www///var/www/www.legetimen.no/www/.conf: No such file or directory
	Creating account key
	Account key exists, skip
	Skip register account key
	Creating domain key
	Use length www.legetimen.no
	Create domain key error.

(trying without webroot now)

**Comment by Richard87** [comment]
hmm, that works better :)

**Comment by Neilpang** [comment]
Sorry for the trouble, but we will have a new command line interface soon.

**Comment by Richard87** [comment]
No problem, I love the tool, so excited about the new version :)

**Comment by Neilpang** [comment]
new version V2.0 is released.
please try again.

**Comment by liuxyon** [comment]
me too. i try dns mode in windows 2012R2. 

$ le --renew  -d www.quna.gq
[2016年04月11日  0:08:23] Creating account key
[2016年04月11日  0:08:23] Account key exists, skip
[2016年04月11日  0:08:51] Skip register account key
[2016年04月11日  0:08:51] Creating domain key
[2016年04月11日  0:08:51] Use length 256
[2016年04月11日  0:08:52] Using ec name: prime256v1
[2016年04月11日  0:08:52] Domain key exists, skip
[2016年04月11日  0:08:52] Creating csr
[2016年04月11日  0:08:52] CSR exists, skip
[2016年04月11日  0:08:52] Verify each domain
[2016年04月11日  0:08:53] Verifying:www.quna.gq
[2016年04月11日  0:09:27] www.quna.gq:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: Response does not complete challenge","status":400}
[2016年04月11日  0:09:27] Skip for removeleve

**Comment by liuxyon** [comment]
i am install newest version.

**Comment by Neilpang** [comment]
@liuxyon   Executes me ?


Please re-issue again.

```
le.sh  --issue --force .......
```

**Comment by liuxyon** [comment]
ok. dns mode work now. but it is happen the https://community.letsencrypt.org/t/iis-8-5-building-incorrect-chain-with-lets-encrypt-authority-x3/13320/52

**Comment by Neilpang** [comment]
@liuxyon  it's not the issue that should be discussed here, so close.
