### ISSUE TITLE
Botched my first try. How to redo it?

### ISSUE THREAD

**Issue by sixspot** [Neilpang/le#116]
This is how I tried my first test case (domain names altered to not-shame the guilty): `le issue dns test.foo.com no ec-384`.  Everything looked fine and I received the string, but screwed up the TXT record by neglecting to add the 'test' part.  I got a something 400 error when I tried `le renew test.foo.com`. I fixed the TXT record, poked and prodded at the setup, but got the same error. I saved a copy of `$HOME/.le/`, deleted `$HOME/.le/test.foo.com` and got a shiny new error (below) that persists even after restoring the directory.  How can I rescue that sub-domain?

(FWIW, I tried with again with the main domain and a couple of sub-domains using the SAN style. That worked just fine with `le issue dns foo.com bar.foo.com,baz.foo.com ec-384`, adding the _correct _ TXT records, followed by `le renew foo.com`.)

```
$ le renew test.foo.com
Creating account key
Use default length 2048
Account key exists, skip
Skip register account key
Creating domain key
Use length 2048
Domain key exists, skip
Creating csr
CSR exists, skip
Verify each domain
Getting token for domain=test.foo.com
Getting token for domain=ec-384
new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: DNS name does not have enough labels","status":400}
```

**Comment by Neilpang** [comment]
Sorry for the trouble.  it's fixed now.

96a46cfcd5a35f2a647e714ab5c42cde9f253920

**Comment by sixspot** [comment]
That variable initialization sequence looks important, but my issue was self-inflicted pain.

When I deleted ~/.le/test.foo.com to retry, I neglected the "no" for the SAN/alt-name, as in `le issue dns test.foo.com ec-384`. The command was nice enough to do exactly what I asked, make "ec-384" an alternative name. That's the `Getting token for domain=ec-384` in the output above. It was in the test.foo.conf, test.foo.com.ssl.conf and encrypted in test.foo.com. I deleted the sub-directory again and started over without all the mistakes. It works fine. :)

I realized the error while reading [https://github.com/letsencrypt/letsencrypt/issues/1682](url). The new-authz about a lack of DNS labels  pretty much means the domain name has no dots.

Thanks for the help and the great script!

**Comment by MarcusWolschon** [comment]
96a46cf is part of release 2.0.2 but with 2.0.2 I have the same error:

<pre>
./le.sh renew kleinbetrieb.biz
[Wed Jun 29 18:15:23 CEST 2016] Creating account key
[Wed Jun 29 18:15:23 CEST 2016] Use default length 2048
[Wed Jun 29 18:15:23 CEST 2016] Account key exists, skip
[Wed Jun 29 18:15:24 CEST 2016] Skip register account key
[Wed Jun 29 18:15:24 CEST 2016] Creating domain key
[Wed Jun 29 18:15:24 CEST 2016] Use length 2048
[Wed Jun 29 18:15:24 CEST 2016] Domain key exists, skip
[Wed Jun 29 18:15:24 CEST 2016] Creating csr
[Wed Jun 29 18:15:24 CEST 2016] CSR exists, skip
[Wed Jun 29 18:15:24 CEST 2016] Verify each domain
[Wed Jun 29 18:15:24 CEST 2016] Getting webroot for domain='kleinbetrieb.biz'
[Wed Jun 29 18:15:24 CEST 2016] Getting token for domain='kleinbetrieb.biz'
[Wed Jun 29 18:15:25 CEST 2016] Getting webroot for domain='ec-384'
[Wed Jun 29 18:15:25 CEST 2016] Getting token for domain='ec-384'
[Wed Jun 29 18:15:27 CEST 2016] new-authz error: {
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: DNS name does not have enough labels",
  "status": 400
}</pre>
