### ISSUE TITLE
Slackware 14.2 (-current prerelease) - le is unable to find /etc/httpd/httpd.conf 

### ISSUE THREAD

**Issue by tallship** [Neilpang/le#117]
For some reason, I'm getting the following error when I try to generate a cert:
<snip>
# le  issue  apache mydomain.com
Apache Config file not found='/usr//etc/httpd/httpd.conf'
set up apache error. Report error to me.
</snip>

I'm not sure why it's coming up as /user//etc/httpd/httpd.conf..... but it should just be /etc/httpd/httpd.conf

In standalone mode, I'm getting the error that I have to stop apache first, once I do that, I'm able to issue:

le issue    no    mydomain.com

But not when apache is running and listening to port 80.

So, is all of this going to cause problems 80 days from now when le tries to use standalone method again to reissue the cert instead of apache mode?

How can I fix it in apache mode?

**Comment by Neilpang** [comment]
I'm not at home now.  I will fix it in one day or two.

**Comment by Neilpang** [comment]
Please paste your "apachectl -V" result here.

**Comment by Neilpang** [comment]
I just made a fix for you. d62ee94019cb16af6abca1187271f310fdbea215
please try again.

**Comment by tallship** [comment]
Here is the output that you requested Neil :)

# apachectl -V
Server version: Apache/2.4.18 (Unix)
Server built:   Mar  1 2016 22:50:57
Server's Module Magic Number: 20120211:52
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/usr"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/var/run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="/etc/httpd/mime.types"
 -D SERVER_CONFIG_FILE="/etc/httpd/httpd.conf"


To... "Try again", do I need to remove or can I just install right over the top  of my earlier installation of LE without losing anything I've already issued and installed certs (and cron) for?

Like this?:

/root# git clone https://github.com/Neilpang/le.git
/root# cd le
/root# ./le.sh install

I ask because I already have the aliases and cronjob from the previous install.

Thanks!

**Comment by tallship** [comment]
What I did was remove the /root/.le directory and then I received the following error once I recloned le from the repo:
 ```
# le issue apache host.domain.info
AH00526: Syntax error on line 476 of /etc/httpd/extra/httpd-ssl.conf:
SSLCertificateFile: file '/etc/httpd/ssl/host.domain.info/host.domain.info.cer' does not exist or is empty
AH00526: Syntax error on line 476 of /etc/httpd/extra/httpd-ssl.conf:
SSLCertificateFile: file '/etc/httpd/ssl/host.domain.info/host.domain.info.cer' does not exist or is empty
Apache Config file not found='/'
set up apache error. Report error to me.
```

Odd that it reports that error twice.

It's now running le version 1.2.1

So now I try it in webroot mode (I've obviously changed the ServerName to host.domain.info for the purposes of this report:

```
:~/.le# ./le.sh issue /var/www/host.domain.info/htdocs host.domain.info
Creating account key
Use default length 2048
Account key exists, skip
Skip register account key
Creating domain key
Use length 2048
Creating csr
Single domain=host.domain.info
Verify each domain
Getting token for domain=host.domain.info
Verifying:host.domain.info
host.domain.info:Verify error:Invalid response from http://host.domain.info/.well-known/acme-challenge/4umqK4yjTa7Bl0ryuXpK2kqk6mw0a0a0a0a0aLkvhlx1OfIs [1.2.3.4]: 404
```
Webroot mode doesn't look like it's going to work for me since I only enable the hosts over SSL (443), and webroot mode appears to want to talk to port 80.

In my humble opinion, the whole point  of Let's Encrypt is to eliminate HTTP over port 80 in almost all cases by making SSL/TLS the standard for everyone in the coming months/years.

Anyway, so I"m back to having to install the certs in standalone mode by stopping apache first like so:

```
# /etc/rc.d/rc.httpd stop
# le issue no host.domain.com
# le installcert host.domain.com /etc/httpd/ssl/host.domain.com/host.domain.com.cer /etc/httpd/ssl/host.domain.com/host.domain.com.key /etc/httpd/ssl/host.domain.com/ca.cer "/etc/rc.d/rc.httpd restart"
```

Doing it this last way works flawlessly - except for one thing... I have to stop the webserver before I run le to issue the cert.

How can I do this on a running webserver that only has support for the virtualhost with SSL/TLS over port 443 for all but the default virtualhost?

**Comment by heldchen** [comment]
le.sh saves the ssl certificates within `/root/.le/` subdirectories. when you removed the directory, you probably also removed the certificates which might explain why apache complained when you tried to reload/restart apache?

**Comment by tallship** [comment]
Thanks @heldchen , but the /etc/httpd/extra/httpd-ssl.conf file specifies /etc/httpd/ssl/domain_name/ as the directory where the cert/key/bundle is kept, and I copy them over there using 

`# le installcert domain_name /etc/httpd/ssl/domain_name/domain_name.cer/key/etc...
`
I'm going to create a non-ssl virtualhost container for one of the virtualhosts and see if the apache method works with that one, and whether or not I still have to stop apache before doing so.

I can always create a server directive or .htaccess file that forces SSL for anyone trying to connect over port 80, and maybe I should do this anyway so people don't always have to put "https://" preceding the hostname in their address bars.

Before I started testing le installcert I was just creating symlinks from /root/.le/domain_name/ to /etc/httpd/ssl/ - which would have exhibited the behavior you suggested - um... arghhh. I better go check the first virtualhost I did this for and make sure I didn't whack that as you suggested ;)

**Comment by Neilpang** [comment]
It was my fault not telling you not to remove `.le` folder.  Do never remove `.le` folder unless you want remove `.le` form your system.   The `.le` contains your private key and cert.  If you remove it , you will lose all of them.


When re-install,  you don't need to remove any file or folder.

just run:
```
le.sh  uninstall
```

And then install again:

```
cd le
./le.sh  install
```

It's safe.  you will not lose any file, such certs, keys, configs etc.
`le.sh` can handle it all automatically.


And in you current case, please manually fix the `httpd-ssl.conf` to work as usual.  And then try our latest code. I think it should work for you.

You never need to stop `apache`,  The `apache` mode is born to work with apache without any interruption.
