### ISSUE TITLE
About multiple domains in the same cert:

### ISSUE THREAD

**Issue by zwl1619** [Neilpang/le#122]
In the documentation:

>Example 2: Multiple domains in the same cert:
```
le issue   /home/wwwroot/aa.com    aa.com    www.aa.com,cp.aa.com
```

If like this:
```
path                                    domain name 
/home/wwwroot/111.aa.com                111.aa.com
/home/wwwroot/222.aa.com                222.aa.com
/home/wwwroot/333.aa.com                333.aa.com
```
How to issue the cert/s? Is one cert  ok?

**Comment by Neilpang** [comment]
please wait a moment.  I'm fixing it.

**Comment by Neilpang** [comment]
I  just checked in v2.0.0.
We have a lot of improvements.

You can uninstall your current version and re-install again. 

You can try with:

```

le.sh  --issue  \
-d  111.aa.com     -w     /home/wwwroot/111.aa.com 
-d  222.aa.com     -w     /home/wwwroot/222.aa.com
-d  333.aa.com     -w     /home/wwwroot/333.aa.com
```

Examples:  https://github.com/Neilpang/le/wiki/How-to-issue-a-cert

**Comment by lucasRolff** [comment]
I love you @Neilpang ! version 2.0!

**Comment by Neilpang** [comment]
@lucasRolff   Love you too !!!
