### ISSUE TITLE
Run standalone server / nc with timeout

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [Neilpang/le#124]
When using the standalone verification method, if for whatever reason (e.g., change in firewall setup after initial certificate issuance, server-side problems at LE, ..) the LE verification server cannot connect to the standalone server, le.sh will hang indefinitely while waiting for a connection using nc. Instead of failing after a short amount of time without any incoming connection, the error will only be noticed when the next cron job fails to start nc on port 80 (usually 24 hours later?).

This seems a bad idea from a security stand point (the standalone server should run for the absolute minimum amount of time since it binds to port 80 and the le.sh runs as root in this situation!). This could easily be remedied by killing the nc process after a certain time.

**Comment by Neilpang** [comment]
Yes,  I will add timeout soon.

**Comment by Neilpang** [comment]
nc time out is added:  63f5d07ed7b1aba14de5fc9714be6f3270a8b35f

If there is any error,  we will kill the nc process.
