### ISSUE TITLE
How I do Auto config in windows 

### ISSUE THREAD

**Issue by liuxyon** [Neilpang/le#126]
How I do auto config --webroot in windows 2012 IIS.
if it is can auto find domain bind path and add cert is better.  

I think may setup choice what for using like IIS or other web service.

**Comment by Neilpang** [comment]
如果你用的 cygwin 的话. 这个路径指向 c盘:  /cygdrive/c/inetpub/wwwroot

大概是这个样子.

**Comment by liuxyon** [comment]
能否设置自动发现域名绑定的路径,例如IIS. 这样如果有很多域名，不用每个去设置. 域名证书时间短再加上域名多的话，是非常大的工作量. 可以在配置文件里设置从哪获取域名绑定路径，例如IIS 或者其它.

**Comment by Neilpang** [comment]
这个没办法支持.  不知道如何自动发现绑定路径.

如果你域名很多, 可以写自定义脚本来 调用 le.sh.
