### ISSUE TITLE
Sugguest setting ttl=1 when using dns-api

### ISSUE THREAD

**Issue by boin** [Neilpang/le#128]
Usually dnspod has a default value with TXT record ttl = 300s. 
We can manually set ttl = 1 when Create/Updating records.

**Comment by Neilpang** [comment]
1. 没必要设 1， 这样会增加 dnspod 的负担。  实际测试，都是实时更新的， 所以不存在延迟的问题。
2. 没有实际测试过， 但是我猜 dnspod 后台可能有限制，免费版的用户不能小于2分钟。
