### ISSUE TITLE
nginx reload not parsed correctly

### ISSUE THREAD

**Issue by yaccin** [Neilpang/le#17]
I used this command to set everything up:

`le issue /srv/acme domain.com www.domain.com 2048 /srv/domain.com/ssl/domain.com.chained.crt /srv/somain.com/ssl/domain.com.key "sudo /usr/sbin/service nginx reload"`

/usr/sbin/service is set up for this user to be run with sudo without password.

However in the .le/domain.com/domain.com.conf file the following is set up:

`Le_RealCACertPath="sudo"`
`Le_ReloadCmd="/usr/sbin/service"`

The rest looks ok and i fixed these entries manually, so it is not a big deal for me, but maybe something that can be resolved in an update.

Also thank you for the work, this was the only solution i got working automated :D

**Comment by Neilpang** [comment]
I just fixed it.
Please uninstall the old version and install this new version again. Don't worry, all your certs and configs will stay still.
