### ISSUE TITLE
Unclear commandline options

### ISSUE THREAD

**Issue by ethanpil** [Neilpang/le#19]
In the readme you explain the options:

 `[key-length]|no  [cert-file-path]|no  [key-file-path]|no`

It seems they are optional. What happens if I write `no` ?? Are the certs not issued? Where are they saved?

**Comment by Neilpang** [comment]
Yes, they are optional.
Set it to "no" means you want to ignore it.

For example,  if you give "no" to "key-length",   it will use default length 2048.

And if you give  'no' to 'cert-file-path',  it will not copy the issued cert to the "cert-file-path".

In all the cases, the issued cert will be placed in "~/.le/domain.com/"

**Comment by ethanpil** [comment]
I suggest you add this to the documentation in readme.md

**Comment by Neilpang** [comment]
readme updated.  Thanks.
