### ISSUE TITLE
Just want to say thanks

### ISSUE THREAD

**Issue by lucasRolff** [Neilpang/le#22]
Sadly Github as far as I know has no way (other than giving you a star) of saying thanks!

We as a hosting company implemented Let's Encrypt using the official client, not only it has too many dependencies, but they basically removed some functionality that made it almost impossible to issue certificates for our customers.

Saw your script, gave it a test - works like charm! So I just wanted to say thanks on behalf of our company.

That also means we might actually be able to contribute! One nice feature (That I really like from the official client) is that you can define multiple web-roots - also if you want to create a SAN certificate this would be a great feature in this script, but I'll see if I can come up with a way to do it, and submit a pull request!

**Comment by Neilpang** [comment]
Thanks.
I'm glad to see it's working for you.

If you are running apache, there is another option "apache" mode, in which you don't need to specify any webroot folder.

**Comment by lucasRolff** [comment]
We do use cPanel, and I actually prefer the webroot way of doing it
