### ISSUE TITLE
How to generate fullchain.pem in webroot mode?

### ISSUE THREAD

**Issue by smoothdvd** [Neilpang/le#24]

**Comment by Neilpang** [comment]
just concat the "~/.le/domain.com/ca.cer"  and "~/.le/domain.com/domain.com.cer"

**Comment by smoothdvd** [comment]
Thanks, I will try it later.

**Comment by markogresak** [comment]
Could this be changed so it's also one of the files, like `[domain.name]/fullchain.pem`?

**Comment by Neilpang** [comment]
Please just concat the "~/.le/domain.com/ca.cer" and "~/.le/domain.com/domain.com.cer" as you needed in the "reload command".

**Comment by Neilpang** [comment]
I just fixed it:  If the real cert path equals to the ca cert path, we will append the ca cert to the domain cert, which makes it a fullchain.

I hope you like it.

**Comment by smoothdvd** [comment]
@Neilpang Thanks

**Comment by oliwarner** [comment]
@Neilpang I didn't understand your last comment. How does this actually work in practice? With an example of `example.com`, how would you do this automatically on issue (and renew)?

**Comment by Neilpang** [comment]
For example:
```
le.sh  issue  /www/aa.com    aa.com 
```

Install cert:
```
le.sh  installcert     /www/conf/domain.cert    /www/conf/domain.key      /www/conf/domain.cert
```
Take care of the  first path ` /www/conf/domain.cert`  and the last path ` /www/conf/domain.cert`.
They are the same path.

So, `le` will  concat the domain.cer and the ca.cer to the path ` /www/conf/domain.cert`.

Which means, the file ` /www/conf/domain.cert` is the `fullchain.pem` you want.
