### ISSUE TITLE
Standalone mode, nc -q 1 : bad argument

### ISSUE THREAD

**Issue by MatMoul** [Neilpang/le#36]
Hi,
I just tested the script in standalone mode and I encounter an error on line 227 and 229.
man nc (-q arg does not exist)
I removed it and the script works.

**Comment by Neilpang** [comment]
What is your nc version?

**Comment by MatMoul** [comment]
I use your script on CentOS7 for my Zimbra Server.
nc --version
Ncat: Version 6.40 ( http://nmap.org/ncat )

**Comment by Neilpang** [comment]
fixed,  please try again.

**Comment by MatMoul** [comment]
Corrections seem OK
good luck for your very best project than letsencrypt
