### ISSUE TITLE
nginx: [emerg] cannot get certificate

### ISSUE THREAD

**Issue by jamimes** [Neilpang/le#4]
重启nginx的时候提示这个，是什么引起的？   环境是 oneinstack 安装的
nginx: [emerg] cannot get certificate (SSL: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:Type=X509)
configuration file /usr/local/tengine/conf/nginx.conf test failed

下面是配置文件内容
----------------------------------------------------------------------------------------
server {
listen 443 ssl spdy;
ssl_certificate /root/.le/www.xxxxx.com/www.xxxxx.com.cer;
ssl_certificate_key /root/.le/www.xxxxx.com/www.xxxxx.com.key;
ssl_session_timeout 10m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:RC4-SHA:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!DSS:!PKS;
ssl_session_cache builtin:1000 shared:SSL:10m;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
server_name www.xxxxx.com xxxxx.com;
access_log /data/wwwlogs/www.xxxxx.com_nginx.log combined;
index index.html index.htm index.php;
root /data/wwwroot/www.xxxxx.com;
if ($host != www.xxxxx.com) {
	rewrite ^/(.*)$ $scheme://www.xxxxx.com/$1 permanent;
	}

location / {
    try_files $uri @apache;
    }
location @apache {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
    }
location ~ .*\.(php|php5|cgi|pl)?$ {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
    }
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|ico)$ {
    expires 30d;
    access_log off;
    }
location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
    }
}

**Comment by Neilpang** [comment]
能把证书贴出来吗?

**Comment by jamimes** [comment]
不好意思，刚刚把系统重装了。我重新配置一下环境，再试试看

**Comment by Neilpang** [comment]
刚才的一次修复导致证书格式错误, 现在已经修复了. 你再试试.

**Comment by jamimes** [comment]
好的。

**Comment by jamimes** [comment]
成功了。 生成出来多了一个ca.cer用来干什么的？

**Comment by Neilpang** [comment]
是中间证书链.
