### ISSUE TITLE
Certificate revocation should be supported

### ISSUE THREAD

**Issue by oskar456** [Neilpang/le#47]
Thanks for this tool. I'm just testing it and found out there is no support for revoking certificates. I think something like that should be added.

**Comment by Neilpang** [comment]
yes, no revoking yet.
Is there any strong requirements to revoke a cert ?

**Comment by lucasRolff** [comment]
Would be cool to be able to revoke it, if let's say - it gets compromised
But then people have bigger issues if their certificates gets compromised anyway :+1:

**Comment by oskar456** [comment]
According to [Let's Encrypt subscriber agreement](https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf) you are obliged to revoke certificate not only when the private key is lost or stolen, but also when "any information in Your Certificate is no longer accurate, current or complete, or any such information becomes misleading." IMO this also includes for instance losing ownership of a domain for which a certificate is issued.

So I'd like to be ready for that. I already revoked a certificate manually, sourcing the `le.sh` script and calling private function `_send_signed_request()`.  The only problem is the generation of JWK account key is buried inside `issue()` function (lines 556 to 575). It this part was factored out to some other private function, manual revocation would be much simpler.

**Comment by dan-ding** [comment]
+1

**Comment by Neilpang** [comment]
`revoke`  is supported now:  6cb415f57e9afd0b06b6ea236f5ab86278179127

**Comment by dan-ding** [comment]
:ice_cream:
