### ISSUE TITLE
ACCOUNT_EMAIL ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/le#50]
From looking at the code in le, to register an email address just do

only once at install ?
`ACCOUNT_EMAIL=email@domain.com le.sh install`

or everytime when issuing a cert ?
`ACCOUNT_EMAIL=email@domain.com le issue`

**Comment by Neilpang** [comment]
when you issue the first cert,  it will create the your account with the "ACCOUNT_EMAIL".

After that, when you issue more certs,  it will not create account, but use the first account.

So, account email is only used the first time.

**Comment by centminmod** [comment]
okay so this is correct ?

`ACCOUNT_EMAIL=email@domain.com le.sh install`

**Comment by Neilpang** [comment]
yes, we already have.

Create if not existing:
==============
~/.le/account.conf
==============

You can write in:
====================
STAGE=1
ACCOUNT_EMAIL="fdsfsfdsfsf"
====================

It will be loaded as you expected.

**Comment by centminmod** [comment]
awesome thanks @Neilpang :)

**Comment by guestisp** [comment]
Just a question: i've not "installed" the client and not set any ACCOUNT_EMAIL but acme.sh is still able to register and issue certificates.

in this case, which account was registered? It is safe ?

**Comment by Neilpang** [comment]
@guestisp 

Yes, it's safe.

the account email is not a MUST  in acme protocol.

If you don't supply the email,  it's ok to go without an email.
