### ISSUE TITLE
setting Le_ReloadCmd

### ISSUE THREAD

**Issue by centminmod** [Neilpang/le#57]
Hi just need some clarification of how to populate and set the `Le_ReloadCmd` flag from the below code

does that mean to set flag to say `/usr/bin/ngxreload` I would need use command for subdomain `sub.a.com`

```
le issue /path/to/webroot sub.a.com no 4096 no no no /usr/bin/ngxreload
```

??

```
issue() {
  if [ -z "$2" ] ; then
    _err "Usage: le  issue  webroot|no|apache|dns   a.com  [www.a.com,b.com,c.com]|no   [key-length]|no"
    return 1
  fi
  Le_Webroot="$1"
  Le_Domain="$2"
  Le_Alt="$3"
  Le_Keylength="$4"
  Le_RealCertPath="$5"
  Le_RealKeyPath="$6"
  Le_RealCACertPath="$7"
  Le_ReloadCmd="$8"
 
  _initpath $Le_Domain
  
  if [ -f "$DOMAIN_CONF" ] ; then
    Le_NextRenewTime=$(grep "^Le_NextRenewTime=" "$DOMAIN_CONF" | cut -d '=' -f 2)
    if [ -z "$FORCE" ] && [ "$Le_NextRenewTime" ] && [ "$(date -u "+%s" )" -lt "$Le_NextRenewTime" ] ; then 
      _info "Skip, Next renewal time is: $(grep "^Le_NextRenewTimeStr" "$DOMAIN_CONF" | cut -d '=' -f 2)"
      return 2
    fi
  fi
  
  if [ "$Le_Alt" == "no" ] ; then
    Le_Alt=""
  fi
  if [ "$Le_Keylength" == "no" ] ; then
    Le_Keylength=""
  fi
  if [ "$Le_RealCertPath" == "no" ] ; then
    Le_RealCertPath=""
  fi
  if [ "$Le_RealKeyPath" == "no" ] ; then
    Le_RealKeyPath=""
  fi
  if [ "$Le_RealCACertPath" == "no" ] ; then
    Le_RealCACertPath=""
  fi
  if [ "$Le_ReloadCmd" == "no" ] ; then
    Le_ReloadCmd=""
  fi
```

**Comment by Neilpang** [comment]
yes,  you are correct.
But it's not recommended to use like that anymore.

The recommended way is like:
```
le  issue    /path/to/webroot   a.com   sub.a.com  no 4096
```

Then call `installcert` command:
```
le.sh    installcert   domain.com    [cert-file-path]|no     [key-file-path]|no     [ca-cert-file-path]|no      [reloadCmd]|no
```

**Comment by centminmod** [comment]
I am trying to use webroot method of authentication with my LEMP stack but the renewal cron for webroot has a empty `Le_ReloadCmd=" "` variable in the domain's `/root/.le/domain.com/domain.conf`

Just an idea of my LEMP stack installer's letsencrypt integration with official client http://centminmod.com/letsencrypt-freessl.html and now with optional integration of your le client at https://community.centminmod.com/posts/25226/ :)

For official letsencrypt client, i had to spin my own auto renewal cron script. But the nice thing about your le script is has renewal already taken care of somewhat. Just `/root/.le/domain.com/domain.conf` has empty `Le_ReloadCmd=" "` variable after i ran

`STAGE=1 /usr/local/bin/le issue /home/nginx/domains/${vhostname}/public ${vhostname} no 2048`

**Comment by centminmod** [comment]
Oh i see it's an additional step after the issuance of the SSL cert to run

`le.sh installcert domain.com /root/.le/domain.com/domain.com/cer /root/.le/domain.com/domain.com.key /root/.le/domain.com/ca.cer /usr/bin/ngxreload`

**Comment by Neilpang** [comment]
Cool,  Both ways are  supported. you can use as you prefer.


Please make sure  the param "cert-file-path"  is not the cert path in the .le folder, but is the path which the nginx really uses.
For example:
On my server, my nginx uses cert from: `/home/admin/conf/web/ssl.aa.com.cert` and  `/home/admin/conf/web/ssl.aa.com.key`


So, the command should be like:
```
le.sh install cert  aa.com    /home/admin/conf/web/ssl.aa.com.cert  /home/admin/conf/web/ssl.aa.com.key   /home/admin/conf/web/ca.cert    "service apache2 reload"
```


Which means after le renews the cert, it will  write the cert and key to `/home/admin/conf/web/ssl.aa.com.cert `  and `/home/admin/conf/web/ssl.aa.com.key`.
The call  "service apache2 reload"


Another trick is you can set the param "[ca-cert-file-path]" same as "[cert-file-path]", then the ca.cert will be appended to the domain "[cert-file-path]" file.

**Comment by Neilpang** [comment]
I read your post.  We have change today.
We don't write to ` /usr/local/bin/le` any more.

just write to `~/.le` folder and  add alias to it.

**Comment by centminmod** [comment]
> Another trick is you can set the param "[ca-cert-file-path]" same as "[cert-file-path]", then the ca.cert will be appended to the domain "[cert-file-path]" file.

awsome didn't know that !

ah yes just tested and /usr/local/bin/le is no more it seems

**Comment by Neilpang** [comment]
No difference.  just for convenience.  Please remove  `le` and `le.sh`,  uninstall it and install the latest version again.

There will be only one `/root/.le/le.sh` there.

**Comment by centminmod** [comment]
thanks @Neilpang looks to be all working now :)
