### ISSUE TITLE
Error message when hitting rate limit

### ISSUE THREAD

**Issue by heldchen** [Neilpang/le#62]
when hitting the rate limits for certificates per domain & week, letsencrypt.org returns a `429` response. `le.sh` should handle it and inform the user. currently there's just an empty error message outputted:

```
...
Verifying:my.domain.org
Success
Verify finished, start to sign.
Sign failed:
```

the contents of `curl.header` is 
```
HTTP/1.1 100 Continue
Expires: Fri, 05 Feb 2016 18:18:17 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 429 Unknown
Server: nginx
Content-Type: application/problem+json
Content-Length: 142
Replay-Nonce: LzW9_1jn3SFxJ7ypBRKdmVkn3M0ZW5dG1EVQZU_viD0
Expires: Fri, 05 Feb 2016 18:18:17 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 05 Feb 2016 18:18:17 GMT
Connection: close

```

the json body payload would contain the exact error message but is not shown:
`{"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: domain.org","status":429}`

**Comment by Neilpang** [comment]
fixed.  please try again.

**Comment by heldchen** [comment]
thanks, alot works as expected now:
```
Success
Verify finished, start to sign.
Sign failed: "detail":"Error creating new cert :: Too many certificates already issued for: domain.org"
```
