### ISSUE TITLE
Check remaining validity before renewing

### ISSUE THREAD

**Issue by rmhrisk** [Neilpang/le#66]
Scott posted this today, seems like it could be relevant to this : https://github.com/ScottHelme/Lets-Encrypt-Smart-Renew

**Comment by heldchen** [comment]
it seems `le.sh` already does this - `renew `only renews a certificate if its remaining validity is 10 or less days *unless* you force it to ignore the validity date by setting `FORCE=1`

**Comment by Neilpang** [comment]
Yes,  we did check it.  we only renew the cert every 80 days by default.
