### ISSUE TITLE
用了cloudxns 的api ，结果并不能自动添加TXT记录。

### ISSUE THREAD

**Issue by rememberli** [Neilpang/le#71]
Add the following TXT record:
Domain: _acme-challenge.xxx.com
TXT value: wP-0cCLJ2SKkhUdG2CVlR-GrX1hUKj3cK5EWxXbw2KA
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.xxx.com
Please add the TXT records to the domains, and retry again.

**Comment by Neilpang** [comment]
需要先去 官方 创建自己的 api key 和id
然后 : 
```
export CX_Key="1234"

export CX_Secret="sADDsdasdgdsf"
```

然后再来:
```
le.sh   issue   dns-cx   aa.com  www.aa.com
```

**Comment by rememberli** [comment]
不是，其实是不会自动下载dnsapi里面的dns-cx.sh, 我手工下载了就可以了。
只是我今天测了太多次，被服务器封掉不给我签了。

**Comment by Neilpang** [comment]
是的, 不会自动下载.
如果你安装了旧版本的, 请先卸载: 
```
le uninstall
```

然后 clone 最新版的源码, 重新安装.

```
./le.sh  install
```

不用担心,  卸载和安装不会丢失你之前的任何证书和设置. 是安全的.

查看版本号:
```
le  version
```
