### ISSUE TITLE
Automatic CloudFlare DNS fails for Free plans?

### ISSUE THREAD

**Issue by gamerjota** [Neilpang/le#77]
Hey there!
I've been trying to automatize the process of renewing my certificates with le using the automatic CloudFlare API integration, I've tried with all my domains on my account, all of them are "Free plan" except for one that is "Pro plan", somehow it only works for the "Pro plan" one and the others end up in an Error without number.

> Error
> Error add txt for domain:_acme-challenge.example.com

The v4 API documentation states that creating and updating DNS records into a zone is available for all plans.
Did anyone experience something similar with Free plans?
I opened a support ticket with CloudFlare explaining the problem and I'll post the answer in here when I get one
.
Cheers!

**Comment by Neilpang** [comment]
I just tested again.  It works for my domain in the Free plan.

I don't have a Pro plan, So, all the tests were done in the Free plan.

Please check your api key and api email.  I noticed in the the cloud flare dashboard, there are two api keys.

Please use the domain key.

**Comment by Neilpang** [comment]
If it still doesn't work for you , please paste the full output here.  you can remove anything domain specific info from it.

**Comment by gamerjota** [comment]
I'm using the Global API key from the Dashboard, not the Origin CA one.
All the domains are under the same account.

This is the otuput for the dns-cf.sh part with debug enabled, happens with any Free plan domain:

`d_api=/root/.le/dnsapi/dns-cf.sh
Found domain api file: /root/.le/dnsapi/dns-cf.sh
dns-cf-add
OK
/root/.le/account.conf:31:CF_Key=[GLOBAL API KEY CENSORED]
OK
/root/.le/account.conf:32:CF_Email=[E-MAIL CENSORED]
First detect the root zone
zones?name=example.com
response={"result":[{"id":"9240656f9ffbf4fbe41b993a77bbb3d8","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-3186837,"name_servers":["simon.ns.cloudflare.com","tani.ns.cloudflare.com"],"original_name_servers":null,"original_registrar":null,"original_dnshost":null,"modified_on":"2016-02-25T01:03:38.823519Z","created_on":"2015-03-15T15:44:39.087067Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":"3","phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"d227b41fb30568df76e29decb6e51315","email":"gamerjota@live.cl"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","legacy_id":"free","is_subscribed":true,"can_subscribe":true,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
{"result":[{"id":"9240656f9ffbf4fbe41b993a77bbb3d8","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-3186837,"name_servers":["simon.ns.cloudflare.com","tani.ns.cloudflare.com"],"original_name_servers":null,"original_registrar":null,"original_dnshost":null,"modified_on":"2016-02-25T01:03:38.823519Z","created_on":"2015-03-15T15:44:39.087067Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":"3","phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"d227b41fb30568df76e29decb6e51315","email":"gamerjota@live.cl"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free
Getting txt records
/zones/9240656f9ffbf4fbe41b993a77bbb3d8=d227b41fb30568df76e29decb6e51315
error /zones/9240656f9ffbf4fbe41b993a77bbb3d8
d227b41fb30568df76e29decb6e51315
0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee/dns_records?type=TXT&name=_acme-challenge.example.com
Error
Error add txt for domain:_acme-challenge.example.com`

And by pasting this I just noticed something? The type of the plan is in the GET request as I can see? Or is it supossed to be there?

> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee

Not sure, I hope this log can help in something.
Thanks!

**Comment by gamerjota** [comment]
> Getting txt records
> /zones/9240656f9ffbf4fbe41b993a77bbb3d8=d227b41fb30568df76e29decb6e51315
> error /zones/9240656f9ffbf4fbe41b993a77bbb3d8
> d227b41fb30568df76e29decb6e51315
> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee/dns_records?type=TXT&name=_acme-challenge.example.com
> Error
> Error add txt for domain:_acme-challenge.example.com

I just noticed something, what the hell is doing the plan ID in the request?

> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee

Also still can't make it work.

**Comment by Neilpang** [comment]
I just added more debug info. Please update and try again.
If it still doesn't work.  Please paste both the free plan debug log and you pro plan debug log.

**Comment by gamerjota** [comment]
_dns-csf_ part only.

Pro plan (Successful):

> dns-cf-add
> OK
> /root/.le/account.conf:13:CF_Key=[CF API KEY]
> OK
> /root/.le/account.conf:15:CF_Email=[CF E-MAIL]
> First detect the root zone
> zones?name=example.com
> response={"result":[{"id":"520c11a19f1db7a38cc2d00671f72f49","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-1670535,"name_servers":["simon.ns.cloudflare.com","tani.ns.cloudflare.com"],"original_name_servers":["dns1.registrar-servers.com","dns5.registrar-servers.com","dns4.registrar-servers.com","dns3.registrar-servers.com","dns2.registrar-servers.com"],"original_registrar":"enom, inc.","original_dnshost":null,"modified_on":"2016-02-25T02:31:26.778311Z","created_on":"2015-06-07T22:49:35.803682Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":"20","phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"d227b41fb30568df76e29decb6e51315","email":"[CF E-MAIL]"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"a577b510288e82b26486fd1df47000ec","name":"Pro Website","price":20,"currency":"USD","frequency":"monthly","legacy_id":"pro","is_subscribed":true,"can_subscribe":true,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
> {"result":[{"id":"520c11a19f1db7a38cc2d00671f72f49","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-1670535,"name_servers":["simon.ns.cloudflare.com","tani.ns.cloudflare.com"],"original_name_servers":["dns1.registrar-servers.com","dns5.registrar-servers.com","dns4.registrar-servers.com","dns3.registrar-servers.com","dns2.registrar-servers.com"],"original_registrar":"enom,
> _domain_id=520c11a19f1db7a38cc2d00671f72f49
> _sub_domain=_acme-challenge
> _domain=example.com
> Getting txt records
> /zones/520c11a19f1db7a38cc2d00671f72f49/dns_records?type=TXT&name=_acme-challenge.example.com
> response={"result":[{"id":"c1989fc0b637f89c4fc1d107a371707d","type":"TXT","name":"_acme-challenge.example.com","content":"9ld-iPy_-nzeugBJJxp4sYsUfNkTIhKLbpKGIO9T_6E","proxiable":false,"proxied":false,"ttl":1,"locked":false,"zone_id":"520c11a19f1db7a38cc2d00671f72f49","zone_name":"example.com","modified_on":"2016-02-25T02:31:26.778311Z","created_on":"2016-02-25T02:31:26.778311Z","meta":{"auto_added":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
> Updating record
And then of course continues without errors.

Free plan (Failed):

> dns-cf-add
> OK
> /root/.le/account.conf:13:CF_Key=[CF API KEY]
> OK
> /root/.le/account.conf:15:CF_Email=[CF E-MAIL]
> First detect the root zone
> zones?name=example.com
> response={"result":[{"id":"8f0d6376af99de3071ae96fa1c56a3f1","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-4195942,"name_servers":["donald.ns.cloudflare.com","lorna.ns.cloudflare.com"],"original_name_servers":null,"original_registrar":"","original_dnshost":null,"modified_on":"2016-02-24T14:34:32.000133Z","created_on":"2014-09-13T02:53:21.486402Z","meta":{"step":2,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":"3","phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"d227b41fb30568df76e29decb6e51315","email":"[CF E-MAIL]"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","legacy_id":"free","is_subscribed":true,"can_subscribe":true,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
> {"result":[{"id":"8f0d6376af99de3071ae96fa1c56a3f1","name":"example.com","status":"active","paused":false,"type":"full","development_mode":-4195942,"name_servers":["donald.ns.cloudflare.com","lorna.ns.cloudflare.com"],"original_name_servers":null,"original_registrar":"","original_dnshost":null,"modified_on":"2016-02-24T14:34:32.000133Z","created_on":"2014-09-13T02:53:21.486402Z","meta":{"step":2,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":"3","phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"d227b41fb30568df76e29decb6e51315","email":"[CF E-MAIL]"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free
> _domain_id=8f0d6376af99de3071ae96fa1c56a3f1
> d227b41fb30568df76e29decb6e51315
> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee
> _sub_domain=_acme-challenge
> _domain=example.com
> Getting txt records
> /zones/8f0d6376af99de3071ae96fa1c56a3f1=d227b41fb30568df76e29decb6e51315
> error /zones/8f0d6376af99de3071ae96fa1c56a3f1
> d227b41fb30568df76e29decb6e51315
> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee/dns_records?type=TXT&name=_acme-challenge.example.com
> Error
> Error add txt for domain:_acme-challenge.example.com
Here the bash stops.

As I can see both user ID:
> d227b41fb30568df76e29decb6e51315
And plan ID:
> 0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee
Are being added to the request.

**Comment by Neilpang** [comment]
Thanks.
I just noticed that too.
It's fixed now, please retry.

**Comment by gamerjota** [comment]
Yep! It's now working, fixed!
Thanks!
