### ISSUE TITLE
le issue fails unless there is service on port 80?

### ISSUE THREAD

**Issue by tallship** [Neilpang/le#78]
USAGE: ./le issue /var/www/hostname.sld.tld/htdocs hostname.sld.tld

Requires that I enable a Virtualhost listening on port 80 for hostname.sld.tld.

Must I have port 80 open and listening for that host or is there a way to allow everything to work on a server that is only serving over port 443?

If I use apache mode instead can I do this without having to expose port 80 and just listen on 443?

Also, I keep my certs in /etc/httpd/ssl/hostname.sld.tld/ and create symlinks to /root/.le/hostname.sld.tld/ for the certs and key, so can I just issue the following which installs the cronjob to renew by default every 80 days?:

le installcert  hostname.sld.tld /root/.le/hostname.sld.tld/hostname.sld.tld.cer  /root/.le/hostname.sld.tld/hostname.sld.tld.key  /root/.le/hostname.sld.tld/ca.cer   "/etc/rc.d/rc.httpd reload"

This would install the cronjob which renews and overwrites the /root/.le/hostname.sld.tld/hostname.sld.tld.cer - right?

If so, I'm thinking to add functionality for 'le issue...' or le issue apache...' to create the symlinks in the respective subdirectory under /etc/httpd/ssl/<hostname>/ for the .key, ca.cer, and <hostname>.cer files.

**Comment by Neilpang** [comment]
I'm not quite understand.

If you server only uses 443 port.  you can use standalone mode.


```
le issue  no   domain.com  
```


Yes, `installcert`  command will copy the cert to the path.

**Comment by tallship** [comment]
Okay I thought standalone mode meant that I'm only running one SSL enabled virtualhost - so as long as the DNS resolves with an A record to this machine's IP address for the hostname I don't need port 80 because I have several VirtualHost containers using SSL via SNI

If that's correct, thank you :)

**Comment by Neilpang** [comment]
just try.

**Comment by schemacs** [comment]
So if I want to use port other than 80, I would do `Le_HTTPPort=81 le issue no domain.com` ?

**Comment by schemacs** [comment]
After reading this [#1357](/letsencrypt/issues/1357) , letsencrypt server only supports 80/443 port.

**Comment by Neilpang** [comment]
@schemacs   Yes,  letsencrypt only support 80/443 port.

The `Le_HTTPPort` is only used in cases that your server is behind a reverse proxy or load balance , and your server is not listening on the standard 80 port.

Then you can define the port here,  but  letsencrypt only connects to your standard 80 port on your public ip.
