### ISSUE TITLE
Support for Multiple Webroots

### ISSUE THREAD

**Issue by wells** [Neilpang/le#80]
I currently run a `letsencrypt-auto` command like:

```
$ /opt/letsencrypt/letsencrypt-auto certonly \
--webroot --agree-tos --keep-until-expiring --rsa-key-size 4096 \
-w /srv/www/domain.com/public -d domain.com -d www.domain.com \
-w /srv/www/subdomain.domain.com/public -d subdomain.domain.com
```

It would be great to be able to request a single webroot cert for multiple webroots and groups of domain names.

**Comment by Neilpang** [comment]
Supported now:

https://github.com/Neilpang/le/issues/122
