### ISSUE TITLE
Add concatenation of site and CA certs for nginx

### ISSUE THREAD

**Issue by salsaly4** [Neilpang/le#83]
Hi!

As nginx requires that CA certificate should be concatenated with site ceritificate, please consider to change installcert to something like that:

```
  if [ "$Le_RealCertPath" ] ; then
    if [ -f "$Le_RealCertPath" ] ; then
      cp -p "$Le_RealCertPath" "$Le_RealCertPath".bak
    fi
    cat "$CERT_PATH" > "$Le_RealCertPath"
    if [[ "$Le_ReloadCmd" =~ "nginx" ]] ; then
      cat "$CA_CERT_PATH" >> "$Le_RealCertPath"
    fi
  fi
```

**Comment by BlueAnanas** [comment]
did you realize that if you put the same file under `/path/to/certfile/in/apache/nginx` and `/path/to/ca/certfile/apache/nginx` like this:

`le installcert j.dom.eu /etc/nginx/ssl-keys/j.dom.eu.crt /etc/nginx/ssl-keys/j.dom.eu.key /etc/nginx/ssl-keys/j.dom.eu.crt "service nginx reload"` 

the concatenation is done for you already?

Maybe I will find a sec add this fact to the readme

**Comment by Neilpang** [comment]
if you want the ca cert and the domain cert concatenated,  please specify the same file path to Le_RealCertPath  and Le_RealCACertPath

for example:

```
le installcert     aa.com        /ssl/aa.com.cert      /ssl/aa.com/aa.com.key   /ssl/aa.com/aa.com.cert
```

**Comment by Neilpang** [comment]
thanks  @BlueAnanas

**Comment by salsaly4** [comment]
Sorry, that was not clear :) Thanks for the script )
