### ISSUE TITLE
Small change required to work with nc on CentOS 5

### ISSUE THREAD

**Issue by TheVillux** [Neilpang/le#88]
On Line 333, I had to make some small adjustments to the nc command so it would work with the native netcat on CentOS 5, basically just removing the -p and making sure _NC was set to "nc". It was an easy fix though, and thanks for such a handy utility.

`333d332`
`<   _NC="nc"`
`336c335`
`<       echo -e -n "HTTP/1.1 200 OK\r\n\r\n$content" | $_NC -l $Le_HTTPPort -v`
`---`
`>       echo -e -n "HTTP/1.1 200 OK\r\n\r\n$content" | $_NC -l -p $Le_HTTPPort -vv`
`338c337`
`<       echo -e -n "HTTP/1.1 200 OK\r\n\r\n$content" | $_NC -l $Le_HTTPPort > /dev/null`
`---`
`>       echo -e -n "HTTP/1.1 200 OK\r\n\r\n$content" | $_NC -l -p $Le_HTTPPort > /dev/null`

**Comment by Neilpang** [comment]
what is your nc version ?

**Comment by TheVillux** [comment]
_nc-1.84-10_
**nc -h**
usage: nc [-46DdhklnrStUuvzC] [-i interval] [-p source_port]
	  [-s source_ip_address] [-T ToS] [-w timeout] [-X proxy_version]
	  [-x proxy_address[:port]] [hostname] [port[s]]
	Command Summary:
		-4		Use IPv4
		-6		Use IPv6
		-D		Enable the debug socket option
		-d		Detach from stdin
		-h		This help text
		-i secs		Delay interval for lines sent, ports scanned
		-k		Keep inbound sockets open for multiple connects
		-l		Listen mode, for inbound connects
		-n		Suppress name/port resolutions
		-p port		Specify local port for remote connects
		-r		Randomize remote ports
 		-s addr		Local source address
		-T ToS		Set IP Type of Service
		-C		Send CRLF as line-ending
		-t		Answer TELNET negotiation
		-U		Use UNIX domain socket
		-u		UDP mode
		-v		Verbose
		-w secs		Timeout for connects and final net reads
		-X proto	Proxy protocol: "4", "5" (SOCKS) or "connect"
		-x addr[:port]	Specify proxy address and port
		-z		Zero-I/O mode [used for scanning]
	Port numbers can be individual or ranges: lo-hi [inclusive]

**Comment by Neilpang** [comment]
It seems that the "-p"  parameter is supported by your `nc`,   why you want to remove `-p` ?

Is there any problem you saw ?

Thanks.

**Comment by TheVillux** [comment]
`-p` doesn't work with `-l` in this version. From the man page:
_-p source_port
             Specifies the source port nc should use, subject to privilege
             restrictions and availability.  It is an error to use this
             option in conjunction with the -l option._

**Comment by Neilpang** [comment]
Thanks,
I just found `-p` is not necessary for all the platforms we support, so, I just removed it.

Thanks again.

**Comment by TheVillux** [comment]
Okay great, thanks again for the utility; very handy.
