### ISSUE TITLE
I can't issue single domain ECC certificate

### ISSUE THREAD

**Issue by ElpoRia** [Neilpang/le#89]
If i trying to create single domain certificate with ecc algorithm, 
le issue /usr/share/nginx/html domain.tld ec-384
using this command, le sets ec-384 as a alternative name.
So it makes error.
How can I issue it?

**Comment by Neilpang** [comment]
please use like this for single domain cert:
```
le issue  /www/root     domain.com     no        ec-384
```

It seems a little ugly, but I will fix it more graceful later.

Thanks.

**Comment by Neilpang** [comment]
If there is an error, please remove the `~/.le/domain.com` folder and try again.

**Comment by ElpoRia** [comment]
Thanks
