### ISSUE TITLE
Not working on alpine linux

### ISSUE THREAD

**Issue by pierreozoux** [Neilpang/le#94]
I just tried to run this on alpine linux, and I get the following error:

```
egrep: bad regex '{[^{]*"type":"http-01"[^}]*': Invalid contents of {}
```

**Comment by Neilpang** [comment]
I just installed a alpine linux.   Can you tell me how to install bash, git and curl  on it?
which command should I use ?

**Comment by pierreozoux** [comment]
`apk --no-cache add git bash openssh curl`

**Comment by Neilpang** [comment]
fixed,  please try again.

**Comment by pierreozoux** [comment]
Yes it is working! Thanks a lot for your project and your help :)

**Comment by itoffshore** [comment]
For the `egrep: bad regex ..... Invalid contents of {}` - [you just need to escape the {}](Invalid contents of {}) causing the error on `busybox egrep`.

**Comment by Neilpang** [comment]
@itoffshore 
Can you pleae give me more info ?

**Comment by itoffshore** [comment]
It looks like you have fixed it @ line 1509 - you escape the first open brace:

`\{[^{]*"type":"http-01"[^}]*`

which works ok in `busybox`

I had the same `Invalid contents of {}`  error in a `logcheck` ignore rule in Alpine.

**Comment by Neilpang** [comment]
@itoffshore   Cool.
